from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict


class AssetBase(BaseModel):
    asset_id: Optional[str] = None
    serial_number: str
    asset_type: str
    capacity: Optional[str] = None
    manufacturer: Optional[str] = None
    manufacturing_date: Optional[date] = None
    refill_date: Optional[date] = None
    expiry_date: Optional[date] = None
    inspection_frequency: Optional[int] = 30
    amc_due_date: Optional[date] = None
    barcode: Optional[str] = None
    remarks: Optional[str] = None
    status: Optional[str] = "Active"


class AssetCreate(AssetBase):
    asset_id: Optional[str] = None  # auto-generated by server if not provided


class AssetUpdate(BaseModel):
    serial_number: Optional[str] = None
    asset_type: Optional[str] = None
    capacity: Optional[str] = None
    manufacturer: Optional[str] = None
    manufacturing_date: Optional[date] = None
    refill_date: Optional[date] = None
    expiry_date: Optional[date] = None
    inspection_frequency: Optional[int] = None
    amc_due_date: Optional[date] = None
    barcode: Optional[str] = None
    remarks: Optional[str] = None
    status: Optional[str] = None


class AssetResponse(AssetBase):
    model_config = ConfigDict(from_attributes=True)
    current_location_id: Optional[str] = None
    photo: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class AssetHistoryResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    asset_id: str
    old_location_id: Optional[str] = None
    new_location_id: Optional[str] = None
    movement_type: Optional[str] = None
    movement_reason: Optional[str] = None
    approval_by: Optional[str] = None
    comments: Optional[str] = None
    movement_date: datetime
    changed_by: Optional[str] = None


class AssetAssignRequest(BaseModel):
    movement_reason: Optional[str] = "Assigned to location"
    movement_type: Optional[str] = "Assigned"
    comments: Optional[str] = None
    force: Optional[bool] = False


from typing import List
class PaginatedAssetResponse(BaseModel):
    items: List[AssetResponse]
    total: int
