"""add_inspection_no

Revision ID: 3d6762a8b54e
Revises: f9b0320ea163
Create Date: 2026-07-27 23:31:36.043125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6762a8b54e'
down_revision: Union[str, None] = 'f9b0320ea163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_no', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inspection_inspection_no'), ['inspection_no'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_inspection_no'))
        batch_op.drop_column('inspection_no')

    # ### end Alembic commands ###
