"""update location model

Revision ID: 9d546d569899
Revises: 9e06f69b39c7
Create Date: 2026-07-23 19:01:55.565372

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d546d569899"
down_revision: Union[str, None] = "9e06f69b39c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("created_by_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_locations_department"), ["department"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_locations_location_name"), ["location_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_locations_plant"), ["plant"], unique=False)
        batch_op.create_unique_constraint(
            "uq_location_name_plant", ["location_name", "plant"]
        )
        batch_op.create_foreign_key(
            "fk_locations_created_by_users", "users", ["created_by_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_locations_created_by_users", type_="foreignkey")
        batch_op.drop_constraint("uq_location_name_plant", type_="unique")
        batch_op.drop_index(batch_op.f("ix_locations_plant"))
        batch_op.drop_index(batch_op.f("ix_locations_location_name"))
        batch_op.drop_index(batch_op.f("ix_locations_department"))
        batch_op.drop_column("created_by_id")
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
