"""Initial enterprise v3 schema

Revision ID: 9e06f69b39c7
Revises:
Create Date: 2026-07-22 22:16:57.624836

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e06f69b39c7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("location_id", sa.String(), nullable=False),
        sa.Column("location_code", sa.String(), nullable=True),
        sa.Column("location_name", sa.String(), nullable=False),
        sa.Column("plant", sa.String(), nullable=True),
        sa.Column("area", sa.String(), nullable=True),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("building", sa.String(), nullable=True),
        sa.Column("floor", sa.String(), nullable=True),
        sa.Column("machine", sa.String(), nullable=True),
        sa.Column("required_asset_type", sa.String(), nullable=True),
        sa.Column("required_capacity", sa.String(), nullable=True),
        sa.Column("risk_category", sa.String(), nullable=True),
        sa.Column("qr_code", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("inspection_frequency", sa.Integer(), nullable=True),
        sa.Column("last_inspection_date", sa.DateTime(), nullable=True),
        sa.Column("gps_lat", sa.Float(), nullable=True),
        sa.Column("gps_lng", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("location_id"),
        sa.UniqueConstraint("qr_code"),
    )
    op.create_index(
        op.f("ix_locations_location_code"), "locations", ["location_code"], unique=True
    )
    op.create_index(
        op.f("ix_locations_location_id"), "locations", ["location_id"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.create_table(
        "plants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plant_code", sa.String(), nullable=True),
        sa.Column("plant_name", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("contact", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plants_id"), "plants", ["id"], unique=False)
    op.create_index(op.f("ix_plants_plant_code"), "plants", ["plant_code"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "system_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_config_id"), "system_config", ["id"], unique=False)
    op.create_index(op.f("ix_system_config_key"), "system_config", ["key"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("plant", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_first_login", sa.Boolean(), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=True),
        sa.Column("last_failed_login", sa.DateTime(), nullable=True),
        sa.Column("last_login_ip", sa.String(), nullable=True),
        sa.Column("last_login_device", sa.String(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_employee_id"), "users", ["employee_id"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=True),
        sa.Column("asset_number", sa.String(), nullable=True),
        sa.Column("asset_type", sa.String(), nullable=True),
        sa.Column("capacity", sa.String(), nullable=True),
        sa.Column("manufacturer", sa.String(), nullable=True),
        sa.Column("manufacturing_date", sa.Date(), nullable=True),
        sa.Column("refill_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("amc_due_date", sa.Date(), nullable=True),
        sa.Column("inspection_frequency", sa.Integer(), nullable=True),
        sa.Column("barcode", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("photo", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("location_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.location_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("asset_id"),
        sa.UniqueConstraint("asset_number"),
        sa.UniqueConstraint("location_id"),
    )
    op.create_index(op.f("ix_assets_asset_id"), "assets", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_assets_serial_number"), "assets", ["serial_number"], unique=True
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("related_id", sa.String(), nullable=True),
        sa.Column("related_type", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("file_type", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attachments_id"), "attachments", ["id"], unique=False)
    op.create_index(
        op.f("ix_attachments_related_id"), "attachments", ["related_id"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_related_type"),
        "attachments",
        ["related_type"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("table_name", sa.String(), nullable=True),
        sa.Column("record_id", sa.String(), nullable=True),
        sa.Column("old_values", sa.Text(), nullable=True),
        sa.Column("new_values", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("device", sa.String(), nullable=True),
        sa.Column("browser", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dept_code", sa.String(), nullable=True),
        sa.Column("dept_name", sa.String(), nullable=True),
        sa.Column("plant_id", sa.Integer(), nullable=True),
        sa.Column("head_name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["plant_id"], ["plants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_departments_dept_code"), "departments", ["dept_code"], unique=True
    )
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("related_id", sa.String(), nullable=True),
        sa.Column("related_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_table(
        "password_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_history_id"), "password_history", ["id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("device_name", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "asset_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(), nullable=True),
        sa.Column("old_location_id", sa.String(), nullable=True),
        sa.Column("new_location_id", sa.String(), nullable=True),
        sa.Column("movement_type", sa.String(), nullable=True),
        sa.Column("movement_reason", sa.String(), nullable=True),
        sa.Column("approval_by", sa.String(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("movement_date", sa.DateTime(), nullable=True),
        sa.Column("changed_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.asset_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asset_history_id"), "asset_history", ["id"], unique=False)
    op.create_table(
        "inspection",
        sa.Column("inspection_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.String(), nullable=True),
        sa.Column("asset_id", sa.String(), nullable=True),
        sa.Column("inspector", sa.String(), nullable=True),
        sa.Column("inspector_id", sa.Integer(), nullable=True),
        sa.Column("inspection_date", sa.DateTime(), nullable=True),
        sa.Column("pressure", sa.String(), nullable=True),
        sa.Column("seal", sa.String(), nullable=True),
        sa.Column("hose", sa.String(), nullable=True),
        sa.Column("pin", sa.String(), nullable=True),
        sa.Column("gauge", sa.String(), nullable=True),
        sa.Column("nozzle", sa.String(), nullable=True),
        sa.Column("mounting", sa.String(), nullable=True),
        sa.Column("visibility", sa.String(), nullable=True),
        sa.Column("accessibility", sa.String(), nullable=True),
        sa.Column("safety_tag", sa.String(), nullable=True),
        sa.Column("cylinder_damage", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("photo", sa.String(), nullable=True),
        sa.Column("overall_status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.asset_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["inspector_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.location_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("inspection_id"),
    )
    op.create_index(
        op.f("ix_inspection_inspection_id"),
        "inspection",
        ["inspection_id"],
        unique=False,
    )
    op.create_table(
        "maintenance",
        sa.Column("maintenance_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(), nullable=True),
        sa.Column("location_id", sa.String(), nullable=True),
        sa.Column("issue", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(), nullable=True),
        sa.Column("assigned_to", sa.String(), nullable=True),
        sa.Column("technician_id", sa.Integer(), nullable=True),
        sa.Column("verified_by", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("opened_date", sa.DateTime(), nullable=True),
        sa.Column("completion_date", sa.DateTime(), nullable=True),
        sa.Column("closed_date", sa.DateTime(), nullable=True),
        sa.Column("inspection_id", sa.Integer(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.asset_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["inspection_id"], ["inspection.inspection_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.location_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["technician_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("maintenance_id"),
    )
    op.create_index(
        op.f("ix_maintenance_maintenance_id"),
        "maintenance",
        ["maintenance_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_maintenance_maintenance_id"), table_name="maintenance")
    op.drop_table("maintenance")
    op.drop_index(op.f("ix_inspection_inspection_id"), table_name="inspection")
    op.drop_table("inspection")
    op.drop_index(op.f("ix_asset_history_id"), table_name="asset_history")
    op.drop_table("asset_history")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_password_history_id"), table_name="password_history")
    op.drop_table("password_history")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_dept_code"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_attachments_related_type"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_related_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_assets_serial_number"), table_name="assets")
    op.drop_index(op.f("ix_assets_asset_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_employee_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_config_key"), table_name="system_config")
    op.drop_index(op.f("ix_system_config_id"), table_name="system_config")
    op.drop_table("system_config")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_plants_plant_code"), table_name="plants")
    op.drop_index(op.f("ix_plants_id"), table_name="plants")
    op.drop_table("plants")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_locations_location_id"), table_name="locations")
    op.drop_index(op.f("ix_locations_location_code"), table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
