"""Add missing foreign key indexes

Revision ID: b42f303a292b
Revises: 875fd407d6f3
Create Date: 2026-07-24 23:01:23.308894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42f303a292b'
down_revision: Union[str, None] = '875fd407d6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_locations')



    op.create_index(op.f('ix_assets_location_id'), 'assets', ['location_id'], unique=False)
    op.create_index(op.f('ix_inspection_asset_id'), 'inspection', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inspection_location_id'), 'inspection', ['location_id'], unique=False)
    op.create_index(op.f('ix_inspection_inspector_id'), 'inspection', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_maintenance_asset_id'), 'maintenance', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_location_id'), 'maintenance', ['location_id'], unique=False)
    op.create_index(op.f('ix_maintenance_technician_id'), 'maintenance', ['technician_id'], unique=False)
    op.create_index(op.f('ix_maintenance_inspection_id'), 'maintenance', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###



    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_maintenance_inspection_id'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_technician_id'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_location_id'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_asset_id'), table_name='maintenance')
    op.drop_index(op.f('ix_inspection_inspector_id'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_location_id'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_asset_id'), table_name='inspection')
    op.drop_index(op.f('ix_assets_location_id'), table_name='assets')

    op.create_table('_alembic_tmp_locations',
    sa.Column('location_id', sa.VARCHAR(), nullable=False),
    sa.Column('location_code', sa.VARCHAR(), nullable=True),
    sa.Column('location_name', sa.VARCHAR(), nullable=False),
    sa.Column('plant', sa.VARCHAR(), nullable=True),
    sa.Column('area', sa.VARCHAR(), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.Column('building', sa.VARCHAR(), nullable=True),
    sa.Column('floor', sa.VARCHAR(), nullable=True),
    sa.Column('machine', sa.VARCHAR(), nullable=True),
    sa.Column('required_asset_type', sa.VARCHAR(), nullable=True),
    sa.Column('required_capacity', sa.VARCHAR(), nullable=True),
    sa.Column('risk_category', sa.VARCHAR(), nullable=True),
    sa.Column('qr_code', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('inspection_frequency', sa.INTEGER(), nullable=True),
    sa.Column('last_inspection_date', sa.DATETIME(), nullable=True),
    sa.Column('gps_lat', sa.FLOAT(), nullable=True),
    sa.Column('gps_lng', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('qr_image_path', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_locations_created_by_users')),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('location_name', 'plant', name=op.f('uq_location_name_plant')),
    sa.UniqueConstraint('qr_code')
    )
    # ### end Alembic commands ###
