"""Phase 3: Database consistency and constraints

Revision ID: f9b0320ea163
Revises: b42f303a292b
Create Date: 2026-07-27 22:03:55.649791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b0320ea163'
down_revision: Union[str, None] = 'b42f303a292b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('attachments', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_attachments_uploaded_by'), ['uploaded_by'], unique=False)

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('location_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('asset_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_uploaded_by'))

    # ### end Alembic commands ###
